name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gcr.io/spectro-dev-public/release/mongo/mongo-sidecar:$(date +%s)
